name: DB-Nota-STG
on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Deploy Database
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        port: 22
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd notadb/nota
          git fetch --all && git checkout staging
          git pull
          cd ../
          ./migrate.sh
          git status
